### ISSUE TITLE
longer timeout possible?

### ISSUE THREAD

**Issue by gallexme** [koudelka/honeydew#71]
hey
i often get 

`** (stop) exited in: GenServer.call(#PID<0.459.0>, {:enqueue, %Honeydew.Job{by: nil, completed_at: nil, enqueued_at: 1548523091425, failure_private: nil, from: nil, job_monitor: nil, private: nil, queue: :vnc_screenshot, result: nil, started_at: nil, task: {:screenshot, [{"x", xxxx}]}}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (honeydew) lib/honeydew.ex:71: Honeydew.async/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
`
anyway to increase it to 50 seconds`?

**Comment by koudelka** [comment]
if it's taking more than five seconds for the queue to enqueue the job, something is quite wrong, the queue should never be that blocked.

can you give me more information about your setup?

what version of honeydew are you using?

which queue type are you using?

it looks like you've got the queue and workers on the same box, how many cores does it have?

can you show me your `start_queue/2`?

**Comment by koudelka** [comment]
> the system is at max load all the time

i think that's your culprit. :)

it'd imagine that the queue process that's timing out isn't getting enough time from the schedulers, as there's so much else going on, leading to the timeout.

if you're running on a low end virtualized machine, you might also not have sufficient IO throughput to support the Mnesia queue writing to the disk. so in addition to high user CPU load, you may also be stalling the CPU from IO-wait.

i don't think i'm going to support a `cast` version of `enqueue/2`, as it's important to know if the job was successfully enqueued, i'd hate to have a user think they'd enqueued a job because honeydew said `:ok`, only to have it never run.

honestly, i don't think that you really want longer timeouts. you're using a disk-backed queue, which indicates (to me) that your jobs aren't easily recreatable, so in essence, Honeydew is acting as a store of state for your application. if the queue is running slowly due to resource limits, that means that its mailbox is backing up, so your jobs are sitting in the volatile in-memory mailbox until the queue can commit them to disk, and since you're hitting timeouts, you've got at least five seconds of jobs piled up in there at any one point in time. if your node crashes, you're going to lose all of those jobs sitting in the mailbox (say, by your OS' OOM killer, since jobs are piling up in memory).

the timeouts are there to indicate that the system isn't meeting processing deadlines that it really should be. if you don't care anyways, just `catch` the exit signal that `enqueue/2` ends up throwing.

**Comment by gallexme** [comment]
Oh I've used the queue before without any options(without mnesia), but it actually hit the timeout way faster, my jobs aren't something I have to worry about if they fail or take ages, I already limited it so that only 50jobs are enqueued at the same time and New jobs are created on demand, but

One job takes atleast 6 seconds to complete and the job is pretty much a gen tcp client waiting for an answer
