### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by l-vincent-l** [koudelka/honeydew#73]
I tried this lib and I can't get examples working.
I cloned the repository and then did a `mix deps.get`, `elixir -S mix run examples/progress_and_queue_status.exs` and I got no output.

I changed the start function to display the status of queues and workers to : 
```
  def start do
    :ok = Honeydew.start_queue(:my_queue)
    :ok = Honeydew.start_workers(:my_queue, HeavyTask, num: 10)
    IO.puts "App started"
    IO.inspect Honeydew.queues
    IO.inspect Honeydew.workers
    IO.inspect Honeydew.status(:my_queue)
  end
```
I have this output:
```
App started
[:my_queue]
[:my_queue]
%{queue: %{count: 0, in_progress: 0, suspended: false}, workers: %{}}
```

what am I doing wrong? I run elixir 1.7.4

**Comment by koudelka** [comment]
Are any of the other examples working for you?

**Comment by l-vincent-l** [comment]
Nop ...

**Comment by koudelka** [comment]
if you manually queue a job with

`{:work_really_hard, [0]} |> Honeydew.async(:my_queue) `

does it display anything?

**Comment by l-vincent-l** [comment]
It displays nothing

**Comment by koudelka** [comment]
You don't even see a `%Honeydew.Job{…}` struct printed?

**Comment by l-vincent-l** [comment]
No.
I wondering if this is normal that when I a do `Honeydew.status(:my_queue)` the result is
```
%{queue: %{count: 0, in_progress: 0, suspended: false}, workers: %{}}
```
Especially the empty workers dict.

**Comment by koudelka** [comment]
Hm, you're right, it shouldn't be empty, I don't know why it is. 

Can you try installing the elixir/erlang versions specified in `.tool_versions`?

**Comment by l-vincent-l** [comment]
The result of `elixir --version` is                                                                                                                                                                                
```
Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.7.4 (compiled with Erlang/OTP 19)
```
is it ok?

**Comment by koudelka** [comment]
Sorry about that, looks like I hadn't pushed the file to github. Here's what I'm using:

```
erlang 21.2.5
elixir 1.8.1
```

If you pull the changes to the repo, it's easy to install the new elixir/erlang versions with `asdf`.

**Comment by l-vincent-l** [comment]
I installed the 1.8 version but it's still not good.
The strange thing is that tests are passing with version 1.7 on travis.
I can't get them passing on my version, here are the results with the version 1.8
```
 1) test simple global queue yield/2 (Honeydew.GlobalTest)
     test/honeydew/global_test.exs:22
     ** (exit) :not_alive
     stacktrace:
       (stdlib) slave.erl:198: :slave.start/5
       (honeydew) test/support/cluster.ex:16: Honeydew.Support.Cluster.spawn_node/1
       (honeydew) test/support/cluster_setups.ex:22: Honeydew.Support.ClusterSetups.start_node/3
       test/honeydew/global_test.exs:9: Honeydew.GlobalTest.__ex_unit_setup_1/1
       test/honeydew/global_test.exs:1: Honeydew.GlobalTest.__ex_unit__/2



  2) test simple global queue hammer async/3 (Honeydew.GlobalTest)
     test/honeydew/global_test.exs:15
     ** (exit) :not_alive
     stacktrace:
       (stdlib) slave.erl:198: :slave.start/5
       (honeydew) test/support/cluster.ex:16: Honeydew.Support.Cluster.spawn_node/1
       (honeydew) test/support/cluster_setups.ex:22: Honeydew.Support.ClusterSetups.start_node/3
       test/honeydew/global_test.exs:9: Honeydew.GlobalTest.__ex_unit_setup_1/1
       test/honeydew/global_test.exs:1: Honeydew.GlobalTest.__ex_unit__/2

.....

  3) test should inform the awaiting process of an uncaught throw (Honeydew.FailureMode.AbandonTest)
     test/honeydew/failure_mode/abandon_test.exs:44
     ** (MatchError) no match of right hand side value: nil
     code: {:error, reason} =
     stacktrace:
       test/honeydew/failure_mode/abandon_test.exs:45: (test)



  4) test should inform the awaiting process of the uncaught throw (Honeydew.FailureMode.MoveTest)
     test/honeydew/failure_mode/move_test.exs:51
     match (=) failed
     code:  assert {:moved, {"intentional crash", stacktrace}} = Honeydew.yield(job)
     right: nil
     stacktrace:
       test/honeydew/failure_mode/move_test.exs:54: (test)



  5) test should inform the awaiting process of an uncaught throw (Honeydew.FailureMode.RetryTest)
     test/honeydew/failure_mode/retry_test.exs:66
     match (=) failed
     code:  assert {:retrying, {"intentional crash", _stacktrace}} = Honeydew.yield(job)
     right: nil
     stacktrace:
       test/honeydew/failure_mode/retry_test.exs:69: (test)



  6) test should remove job from the queue (Honeydew.FailureMode.AbandonTest)
     test/honeydew/failure_mode/abandon_test.exs:24
     No message matching :job_ran after 100ms.
     The process mailbox is empty.
     code: assert_receive :job_ran
     stacktrace:
       test/honeydew/failure_mode/abandon_test.exs:26: (test)



  7) test should move the job on the new queue (Honeydew.FailureMode.MoveTest)
     test/honeydew/failure_mode/move_test.exs:28
     No message matching :job_ran after 100ms.
     The process mailbox is empty.
     code: assert_receive :job_ran
     stacktrace:
       test/honeydew/failure_mode/move_test.exs:30: (test)



  8) test should retry the job (Honeydew.FailureMode.RetryTest)
     test/honeydew/failure_mode/retry_test.exs:37
     No message matching :job_ran after 100ms.
     The process mailbox is empty.
     code: assert_receive :job_ran
     stacktrace:
       test/honeydew/failure_mode/retry_test.exs:39: (test)
```
And then it get stuck

**Comment by koudelka** [comment]
did you install erlang 21.2.5?

**Comment by l-vincent-l** [comment]
Sorry it took some time.
This is working now! thank you for your time!
There are just two errors on `mix test`

```
1) test simple global queue yield/2 (Honeydew.GlobalTest)
     test/honeydew/global_test.exs:22
     ** (exit) :not_alive
     stacktrace:
       (stdlib) slave.erl:198: :slave.start/5
       (honeydew) test/support/cluster.ex:16: Honeydew.Support.Cluster.spawn_node/1
       (honeydew) test/support/cluster_setups.ex:22: Honeydew.Support.ClusterSetups.start_node/3
       test/honeydew/global_test.exs:9: Honeydew.GlobalTest.__ex_unit_setup_1/1
       test/honeydew/global_test.exs:1: Honeydew.GlobalTest.__ex_unit__/2



  2) test simple global queue hammer async/3 (Honeydew.GlobalTest)
     test/honeydew/global_test.exs:15
     ** (exit) :not_alive
     stacktrace:
       (stdlib) slave.erl:198: :slave.start/5
       (honeydew) test/support/cluster.ex:16: Honeydew.Support.Cluster.spawn_node/1
       (honeydew) test/support/cluster_setups.ex:22: Honeydew.Support.ClusterSetups.start_node/3
       test/honeydew/global_test.exs:9: Honeydew.GlobalTest.__ex_unit_setup_1/1
       test/honeydew/global_test.exs:1: Honeydew.GlobalTest.__ex_unit__/2
```
but `progress_and_queue_status` example is now working

**Comment by koudelka** [comment]
No worries, glad it's working. :)

It sounds like there might be an issue in the test suite getting the slave nodes working, It's interesting that it doesn't fail on travis. I'll look into it, thanks!

**Comment by l-vincent-l** [comment]
Thank you very much!
