### ISSUE TITLE
Won't build a release

### ISSUE THREAD

**Issue by timmak** [koudelka/honeydew#9]
Using the mnesia queue seems too break it when trying to build a release with distillery

```
=CRASH REPORT==== 29-Jan-2017::17:29:46 ===
  crasher:
    initial call: Elixir.Honeydew.Queue.Mnesia:init/1
    pid: <0.580.0>
    registered_name: []
    exception exit: {undef,
                        [{mnesia,create_schema,[['queue@127.0.0.1']],[]},
                         {'Elixir.Honeydew.Queue.Mnesia',init,2,
                             [{file,"lib/honeydew/queue/mnesia.ex"},
                              {line,19}]},
                         {'Elixir.Honeydew.Queue.Mnesia',init,1,
                             [{file,"lib/honeydew/queue/mnesia.ex"},{line,2}]},
                         {gen_server,init_it,6,
                             [{file,"gen_server.erl"},{line,328}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:init_it/6 (gen_server.erl, line 352)
    ancestors: ['honeydew.queue_supervisor.global.my_queue',<0.578.0>,
                  <0.574.0>,<0.535.0>]
    messages: []
    links: [<0.579.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 301
  neighbours:
** (EXIT from #PID<0.574.0>) shutdown: failed to start child: Honeydew.QueueSupervisor
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:undef, [{:mnesia, :create_schema, [[:"queue@127.0.0.1"]], []}, {Honeydew.Queue.Mnesia, :init, 2, [file: 'lib/honeydew/queue/mnesia.ex', line: 19]}, {Honeydew.Queue.Mnesia, :init, 1, [file: 'lib/honeydew/queue/mnesia.ex', line: 2]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
            (honeydew) lib/honeydew/queue_supervisor.ex:22: anonymous fn/2 in Honeydew.QueueSupervisor.start_link/6
            (elixir) lib/enum.ex:651: anonymous fn/3 in Enum.each/2
            (elixir) lib/enum.ex:1760: Enum.each/2
            (honeydew) lib/honeydew/queue_supervisor.ex:21: Honeydew.QueueSupervisor.start_link/6
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6

```

**Comment by koudelka** [comment]
Mind posting your test app so I can reproduce the issue?

**Comment by larryweya** [comment]
Ran into the same and solved by adding :mnesia into the extra_applications key within my mix.exs
